name: hourly-taxi-demand-feature-pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Execute Python workflow from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python -m feature_pipeline

